name: Deploy website

on:
  push:
    branches:
      -main

jobs:
  terrafrom:
    name: Deploy infrastructure
    runs-on: ubuntu-latest

    evn: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: ${{ secrets.TF_VAR_region }}
      TF_VAR_iam_user_name: ${{ secrets.TF_VAR_iam_user_name }}
      TF_VAR_bucket_name: ${{ secrets.TF_var_baucket_name }}
      TF_VAR_table_name: ${{ secrets.TF_VAR_table_name }}

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: checkout Repo
        uses: actions.checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: terraform Format
        run: terraform fmt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: treeaform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve